#!/bin/sh

#[ -f /etc/sysctl.conf ] || exit 0

case "$1" in
    start)
        echo "Processing audio"
        /root/startAudio.sh
        ;;

    stop)
        echo "Stopping to process audio"
#        /root/stopGadget.sh
        ;;

    *)
        echo "Usage: $0 start"
        exit 1
        ;;
esac

exit $?
