#!/bin/sh

case "$1" in
    start)
        echo "Starting the micro battery server"
        cd /usr/share/BatteryController; NODE_PATH=/usr/lib/node_modules ./HardwareServer.js &
#        ( while [ true ]; do
#         sleep 10
#          echo `date` restarting >> /root/BatteryController.txt
#          NODE_PATH=/usr/lib/node_modules:/usr/share/BatteryController /usr/share/BatteryController/BatteryControllerEnvoyMeterNet.js
#        done ) &
        ;;

    stop)
        echo "Stopping the micro battery server"
        # killall node ./BatteryControllerEnvoyMeter.js
        hsPID=`ps ax | grep HardwareServer.js | grep node | awk '{print $1}'`
        kill -9 ${hsPID}
        bcPID=`ps ax | grep BatteryController.*js | grep node | awk '{print $1}'`
        if [ ! -z ${bcPID} ]; then
          kill -9 ${bcPID}
        fi
        ;;

    *)
        echo "Usage: $0 start stop"
        exit 1
        ;;
esac

exit $?
