#!/bin/sh

case "$1" in
    start)
        echo "Starting the micro battery server"
        cd /usr/share/BatteryController; NODE_PATH=/usr/lib/node_modules ./HardwareServer.js &
        # find if we are master by reading the state of gpio7
        /usr/share/BatteryController/bash/gpioReserveIn.sh 7
        isMaster=`/usr/share/BatteryController/bash/gpioRead.sh 7`
        if [ ${isMaster} -eq "1" ]; then
          echo setting up as master battery controller
          sleep 10
          NODE_PATH=/usr/lib/node_modules:/usr/share/BatteryController /usr/share/BatteryController/BatteryControllerEnvoyMeterNet.js &
        else
          echo setting up as a slave battery hardware
        fi
        /usr/share/BatteryController/bash/gpioUnexport.sh 7 # free up gpio7
        ;;

    stop)
        echo "Stopping the micro battery server"
        # killall node ./BatteryControllerEnvoyMeter.js
        hsPID=`ps ax | grep HardwareServer.js | grep node | awk '{print $1}'`
        if [ ! -z ${hsPID} ]; then
          kill -9 ${hsPID}
        fi
        bcPID=`ps ax | grep BatteryController.*js | grep node | awk '{print $1}'`
        if [ ! -z ${bcPID} ]; then
          kill -9 ${bcPID}
        fi
        ;;

    *)
        echo "Usage: $0 start stop"
        exit 1
        ;;
esac

exit $?
